//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6_MVC_Images.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Student2
    {
        public int Id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        [DisplayName("Choose Image")]
        public string img_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
