//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4_DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Student
    {
        public int stdid { get; set; }
        public string stdname { get; set; }
        public string stdgender { get; set; }
        public int stdage { get; set; }
        public int stdclass { get; set; }

    }
}
